<?php namespace App\Libraries\Reports;
/**
 * Created By: Sugeng
 * Date: 12/05/20
 * Time: 12.02
 */

class Letter extends \TCPDF
{
    public function Header()
    {
        // Logo
        $path = public_path("assets/registration/img/logo-updm.png");
        $this->Image($path, 10, 8, 24, 23, '', '', '', true, 150);

        // Set font
        $this->SetFont('dejavuserif', 'B', 16);
        // Move to the right
        $this->Cell(7);

        // Line break
        $this->Ln(2);
        $this->Cell(7);
        $this->SetFont('dejavuserif', 'B', 14);
        $this->Cell(180, 10, 'UNIVERSITAS PROF. DR. MOESTOPO (BERAGAMA)', 0, 0, 'C');
        $this->Ln(8);

        $this->SetFont('dejavuserif', 'B', 7);
        $this->Cell(7);
        $this->Cell(180, 5, 'Kampus I  : Jl. Hang Lekir I / 8 Jakarta Pusat 10270 Telp. 7261433 Fax. 7252685', 0, 0, 'C');
        $this->Ln(4);
        $this->Cell(7);
        $this->Cell(180, 5, 'Kampus II : Jl. Bintaro Permai Raya No.3 Jakarta Selatan Telp. 73885254 Fax. 73885253', 0, 0, 'C');
        $this->Ln(4);
        $this->Cell(7);
        $this->Cell(180, 4, 'Kampus III: Jl. Swadarma Raya No. 54 Ululjami Jakarta Selatan Telp. 58902927, 58902928', 0, 0, 'C');
        $this->Ln(4);
        $this->Cell(7);
        $this->Cell(180, 4, 'Website : http://moestopo.ac.id, Email : pmb@moestopo.ac.id', 0, 0, 'C');
        $this->Ln(1);
        $this->Cell(0, 5, " ", "B");
    }

    public function Footer() {
        // Position at 15 mm from bottom
        $this->SetY(-10);
        // Set font
        $this->SetFont('helvetica', 'I', 6);
        // Page number
        $this->Cell(100, 10, "Generated by Universitas Prof. Dr. Moestopo (Beragama)", 0, false, 'L', 0, '', 0, false, 'T', 'M');
        $this->Cell(0, 10, "at " . date("d-m-Y H:i:s"), 0, false, 'R', 0, '', 0, false, 'T', 'M');
    }

    public function MultiCell($w, $h, $txt, $border=0, $align='J', $fill=false, $ln=1, $x='', $y='', $reseth=true, $stretch=0, $ishtml=true, $autopadding=true, $maxh=0, $valign='T', $fitcell=false)
    {
        parent::MultiCell($w, $h, $txt, $border, $align, $fill, $ln, $x, $y, $reseth, $stretch, $ishtml, $autopadding, $maxh, $valign, $fitcell);
    }
}


class GraduateLetter
{
    /**
     * @var Letter
     */
    protected $pdf;

    protected $registrant;
    /**
     * @var \Illuminate\Support\Collection
     */
    protected $tuitions;

    public function __construct()
    {
        $this->pdf = new Letter(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

        $this->pdf->SetCreator(PDF_CREATOR);
        $this->pdf->SetAuthor('Universitas Prof. Dr. Moestopo (Beragama)');
        $this->pdf->SetTitle("Surat Lulus Seleksi Saringan Masuk UPDM(B)");
        $this->pdf->SetSubject('Surat Lulus Seleksi');
        $this->pdf->SetKeywords('Surat, lulus, seleksi, updm');
    }

    public function registrant($registrant)
    {
        $this->registrant = $registrant;
    }

    public function render()
    {
        $this->pdf->SetMargins(PDF_MARGIN_LEFT, 40, PDF_MARGIN_RIGHT);
        $this->pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
        $this->pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

        // set font
        $this->pdf->SetFont('times', '', 11);

        // add a page
        $this->pdf->AddPage();

        $this->pdf->Cell(0, 5, "Kepada", 0, 0, 'L');
        $this->pdf->Ln(5);
        $this->pdf->MultiCell(0, 5, "yth Sdr/i <strong>{$this->registrant->nmmhs}</strong>", 0, 'L', false);
        $this->pdf->MultiCell(0, 5, "Nomor Registrasi : <strong>{$this->registrant->noreg}</strong>", 0, 'L', false);
        $this->pdf->Cell(0, 5, "di tempat", 0, 0, 'L');
        $this->pdf->Ln(10);

        $status_lulus = ($this->registrant->sttes == "L") ? "LULUS" : "LULUS SEBAGAI CADANGAN";

        $this->pdf->MultiCell(0, 5, "
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Berdasarkan hasil seleksi Penerimaan Mahasiswa Baru Tahun
            <strong>{$this->registrant->thusm}</strong> Gelombang <strong>{$this->registrant->kdgel}</strong> Anda dinyatakan <strong>{$status_lulus}</strong> dengan status
            <strong>BARU</strong> pada Program Studi <strong>{$this->registrant->departement->nmjur}</strong> dengan Peringkat
            <strong>{$this->registrant->grusm}</strong>.
    ", 0, 'J', false);

        $this->pdf->Ln(3);
        $this->pdf->MultiCell(0, 5, "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Adapun biaya yang harus dibayarkan adalah sebagai berikut:", 0, 'J', false);

        if ($this->tuitions->count() > 0) {

            $this->pdf->Ln(4);

            $this->pdf->SetFont('times', 'B', 9);
            $this->pdf->Cell(15, 5, "NO.", 1, 0, 'C');
            $this->pdf->Cell(135, 5, "NAMA BIAYA", 1, 0, 'C');
            $this->pdf->Cell(0, 5, "NILAI (Rp.)", 1, 0, 'C');
            $this->pdf->Ln(5);

            $this->pdf->SetFont('times', '', 9);
            $i=0; $total=0;
            foreach ($this->tuitions as $tuition) {
                $i++;
                $this->pdf->Cell(15, 5, str_pad($i, 2, '0', STR_PAD_LEFT).".", 1, 0, 'C');
                $this->pdf->Cell(135, 5, $tuition->nmkod, 1, 0, 'L');
                $this->pdf->Cell(0, 5, number_format($tuition->nlbia, 0, ',', '.'). "   ", 1, 0, 'R');
                $this->pdf->Ln(5);
                $total += $tuition->nlbia;
            }
            $this->pdf->Cell(150, 5, "TOTAL BIAYA", 1, 0, 'R');
            $this->pdf->Cell(0, 5, number_format($total, 0, ',', '.'). "   ", 1, 0, 'R');
            $this->pdf->Ln(10);
        } else {
            $this->pdf->Ln(10);
            $this->pdf->MultiCell(0, 5, "<strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Silakan hubungi bagian PMB untuk biaya mahasiswa baru.</strong>", 0, 'J', false);
            $this->pdf->Ln(10);
        }

        $this->pdf->SetFont('times', '', 11);

        $virtual_account = $this->virtualAccount();
        $this->pdf->MultiCell(0, 5, "Pembayaran uang kuliah dapat dibayarkan melalui Bank BNI'46 dengan nomor rekening (Virtual Account) <strong>{$virtual_account}</strong> atas nama <strong>{$this->registrant->departement->nmjur}</strong>.", 0, 'J', false);

        $this->pdf->Ln(5);
        $this->pdf->MultiCell(0, 5, 'Jika Anda melakukan konfirmasi pembayaran melalui email, tuliskan subjek email: Konfirmasi Pembayaran {No. Registrasi Anda}.', 0, 'J', false);

        $this->pdf->Ln(5);
        $this->pdf->MultiCell(0, 5, "Demikian informasi yang Kami sampaikan, terima kasih atas kepercayaan Anda masuk sebagai Calon Mahasiswa Universitas Prof. Dr. Moestopo (Beragama).", 0, 'J', false);
        $this->pdf->Ln(5);

        $this->information();

        $this->pdf->Ln(10);
        $this->pdf->Cell(130);
        $this->pdf->Cell(0, 5, "Jakarta, " . monthName(date('Y-m-d')), 0, 0, "L");
        $this->pdf->Ln(20);
        $this->pdf->Cell(130);
        $this->pdf->Cell(0, 5, "Panitia PMB UPDM(B)", 0, 0, "L");

        $this->pdf->Output("surat_kelulusan_{$this->registrant->thusm}-{$this->registrant->kdgel}_{$this->registrant->noreg}.pdf", 'I');
    }

    public function tuition(\Illuminate\Support\Collection $tuitions)
    {
        $this->tuitions = $tuitions;
    }

    protected function virtualAccount()
    {
        $faculty = substr($this->registrant->kdju1, 0, 1);

        $virtual_account = array(
            '0' => '988-01122',
            '1' => '988-01112',
            '2' => '988-01132',
            '3' => '988-01142',
            '4' => '988-01152',
            '5' => '988-01162'
        );

        return $virtual_account[$faculty] . '-' . $this->registrant->noreg;
    }

    private function information()
    {
        $faculty = substr($this->registrant->kdju1, 0, 1);

        switch ($faculty) {
            case "1":
                $this->kedokteran();
                break;
            case "2":
                $this->fisip();
                break;
            case "3":
                $this->ekonomi();
                break;
            case "4":
                $this->fikom();
                break;
            case "5":
                $this->teknik();
                break;
        }
    }

    private function fisip()
    {
        $this->pdf->Cell(18, 5, "Telepon     ", 0, 0, 'L');
        $this->pdf->Cell(3, 5, ":", 0, 0, 'C');
        $this->pdf->Cell(0, 5, "(021)-7261474, (021)-7252683", 0, 0, 'L');
        $this->pdf->Ln(5);
        $this->pdf->Cell(18, 5, "Email       ", 0, 0, 'L');
        $this->pdf->Cell(3, 5, ":", 0, 0, 'C');
        $this->pdf->Cell(0, 5, "fisip@moestopo.ac.id", 0, 0, 'L');
    }

    private function ekonomi()
    {
        $this->pdf->Cell(18, 5, "Telepon     ", 0, 0, 'L');
        $this->pdf->Cell(3, 5, ":", 0, 0, 'C');
        $this->pdf->Cell(0, 5, "(021)-7246523", 0, 0, 'L');
        $this->pdf->Ln(5);
        $this->pdf->Cell(18, 5, "Email       ", 0, 0, 'L');
        $this->pdf->Cell(3, 5, ":", 0, 0, 'C');
        $this->pdf->Cell(0, 5, "fe@moestopo.ac.id", 0, 0, 'L');
    }

    private function fikom()
    {
        $this->pdf->Cell(18, 5, "Telepon     ", 0, 0, 'L');
        $this->pdf->Cell(3, 5, ":", 0, 0, 'C');
        $this->pdf->Cell(0, 5, "(021)-7261433", 0, 0, 'L');
        $this->pdf->Ln(5);
        $this->pdf->Cell(18, 5, "Email       ", 0, 0, 'L');
        $this->pdf->Cell(3, 5, ":", 0, 0, 'C');
        $this->pdf->Cell(0, 5, "fikom@moestopo.ac.id", 0, 0, 'L');
    }

    private function teknik()
    {

    }

    private function kedokteran()
    {
        $this->pdf->Cell(18, 5, "Telepon     ", 0, 0, 'L');
        $this->pdf->Cell(3, 5, ":", 0, 0, 'C');
        $this->pdf->Cell(0, 5, "(021) 73885254 ext. 311", 0, 0, 'L');
        $this->pdf->Ln(5);
        $this->pdf->Cell(18, 5, "Fax     ", 0, 0, 'L');
        $this->pdf->Cell(3, 5, ":", 0, 0, 'C');
        $this->pdf->Cell(0, 5, "(021) 7343734", 0, 0, 'L');
        $this->pdf->Ln(5);
        $this->pdf->Cell(18, 5, "Ponsel     ", 0, 0, 'L');
        $this->pdf->Cell(3, 5, ":", 0, 0, 'C');
        $this->pdf->Cell(0, 5, "0813-6240-6525 (Bagian Keuangan)", 0, 0, 'L');
        $this->pdf->Ln(5);
        $this->pdf->Cell(18, 5, "Email       ", 0, 0, 'L');
        $this->pdf->Cell(3, 5, ":", 0, 0, 'C');
        $this->pdf->Cell(0, 5, "keuangan@fkg.moestopo.ac.id", 0, 0, 'L');
    }
}
